#!/bin/bash

startrec(){
	set $(slop -q -o -f '%x %y %w %h')

	ffmpeg -loglevel error \
		-show_region 1 \
		-s ${3}x${4} \
		-r 30 \
		-f x11grab \
		-i :0.0+${1},${2} \
		-f pulse \
		-i default \
		~/"record-$(date '+%a %b %d - %l:%M %p')".mp4
}

stoprec(){
	pkill ffmpeg

	notify-send -t 2000 "recording stopped"
}

pgrep -x ffmpeg > /dev/null && stoprec || startrec
