#!/bin/sh

startrec(){
	set $(slop -q -o -f '%x %y %w %h')

	ffmpeg -loglevel error \
		-show_region 1 \
		-s ${3}x${4} \
		-r 30 \
		-f x11grab \
		-i :0.0+${1},${2} \
		-pix_fmt yuv420p \
		-crf 16 \
		-vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" \
		~/"record-$(date '+%a %b %d - %l:%M %p')".mp4
}

stoprec(){
	pkill ffmpeg

	notify-send -t 2000 "recording stopped"
}

pgrep -x ffmpeg > /dev/null && stoprec || startrec
