#!/bin/bash

startrec(){
	set $(slop -q -o -f '%x %y %w %h')

	notify-send -t 2000 "recording started"

	ffmpeg -y -f x11grab -show_region 1 -s ${3}x${4} \
		-r 30 -i :0.0+${1},${2} -qscale 0 \
		"record-$(date '+%a %b %d - %l:%M %p')".mp4
}

stoprec(){
	pkill ffmpeg

	notify-send -t 2000 "recording stopped"
}

main(){
	if pgrep -x ffmpeg > /dev/null; then
		stoprec
	else
		startrec
	fi
}

main "$@"
